### ISSUE TITLE
Rename the project to kryo-messaging

### ISSUE THREAD

**Issue by ItsKev** [kryonitelabs/kryo-messaging#25]
**Is your feature request related to a problem? Please describe.**
We should provide a better naming scheme for our projects.

**Describe the solution you'd like**
Everything directly related to the kryocloud should be prefixed with kryocloud-* and everything else with kryo-*.

**Describe alternatives you've considered**
Another alternative is capitalized names like KryoCloudInitContainers or KryoMessaging. I would still prefer the naming described above. URLs with capitalized projects look quite ugly.

**Comment by ItsKev** [comment]
@lusu007 what are your thoughts on this?

**Comment by lusu007** [comment]
I totally agree with you that we should stick with dashes (-) between words in a project name. There is nothing uglier than case-sensitive URLs... 😄

If it is okay for you @ItsKev I would take care of this one.
