### ISSUE TITLE
Javadoc is not generated correctly for classes with Lombok annotation

### ISSUE THREAD

**Issue by ItsKev** [kryonitelabs/kryo-messaging#27]
**Describe the bug**
Classes with Lombok annotations are not correctly represented in the Javadoc.

**To Reproduce**
Head over to the projects Javadoc page and open a class with Lombok annotations.
https://kryonitelabs.github.io/messaging/latest/org/kryonite/service/message/Message.html

**Expected behavior**
Getters are visible in the Javadoc.

**Comment by lusu007** [comment]
As described [here](https://stackoverflow.com/a/32312612) the delombok task should be executed before the javadoc task.
